#!/bin/bash
set -x

if [[ ! -d /sugar/tests/unit-php ]]
then
    echo "No unit tests available to run in tests/unit-php"
    exit 1
fi

cd /sugar/tests/unit-php

chmod +x ../../vendor/bin/phpunit
../../vendor/bin/phpunit

exec "$@"
