#!/bin/bash
echo "Applying ownership to $SUGAR_USER_ID:$SUGAR_GROUP_ID"
chown -R "$SUGAR_USER_ID:$SUGAR_GROUP_ID" /sugar

if [ -e ./bin/sugarcrm ]
then
    chmod 700 ./bin/sugarcrm
fi
if [ -e ./vendor/phpunit/phpunit/phpunit ]
then
    chmod 700 ./vendor/phpunit/phpunit/phpunit
fi
find . -type d -exec chmod 775 {} \;
find . -type f ! -name phpunit ! -name sugarcrm -exec chmod 664 {} \;
